"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dict = void 0;
const globals = [];
exports.dict = {
    Program(sections) {
        let code = '';
        sections.children.map(c => { code += c.eval(); });
        code += '\n main() \n // auto generated by the cruton interpreter';
        return code;
    },
    //   hehe
    MAIN(_d, _entry, _, body, _end) {
        return `
    var r1 = null;
    var r2 = null;
    var r3 = null;
    var r4 = null;
    var r5 = null;
    var r6 = null;
    var r7 = null;
    var r8 = null;
    var r9 = null;
    var r10 = null;
function main() {
    ${body.children.map(c => c.eval()).join('   \n')}
}
        `;
    },
    Custom(_, id, _c, body, _end) {
        return `
function ${id.eval()}() {
    ${body.children.map(c => c.eval()).join('\t\n')}
}
        `;
    },
    Import(_import, modulename, _as, id) {
        return `var ${id.eval()} = require(${modulename.eval()})`;
    },
    GLOBALS(_d, _data, _, body, _end) {
        return `
// DATA SECTION
${body.children.map(c => c.eval()).join('\t\n')}
// DATA SECTION END
        `;
    },
    GlobalDecl(id, _, expr, _c) {
        return `var ${id.eval()} = ${expr.eval()}`;
    },
    Expr(or) {
        return or.eval();
    },
    LogicalOr_or(left, _or, right) {
        return `${left.eval()} || ${right.eval()}`;
    },
    LogicalAnd_and(left, _and, right) {
        return `${left.eval()} && ${right.eval()}`;
    },
    Primary_parens(_op, expr, _cp) {
        return `(${expr.eval()})`;
    },
    Primary_not(_, expr) {
        return `!${expr.eval()}`;
    },
    If(_if, condition, _, body, _stop) {
        return `
if(${condition.eval()}) {
    ${body.children.map(c => c.eval()).join('\n')}
}
        `;
    },
    true(_) {
        return `true`;
    },
    false(_) {
        return `false`;
    },
    Call(_call, id, _c, outputTo) {
        if (outputTo.sourceString) {
            return `${outputTo.sourceString} = ${id.eval()}(r1, r2, r3, r4, r5, r6, r7, r8, r9, r10)`;
        }
        else {
            return `${id.eval()}(r1, r2, r3, r4, r5, r6, r7, r8, r9, r10)`;
        }
    },
    Ini(_ini, id, _, expr) {
        if (expr.sourceString) {
            return `let ${id.eval()} = ${expr.eval()};`;
        }
        else {
            return `let ${id.eval()};`;
        }
    },
    Static(_static, id, _, expr) {
        return `const ${id.eval()} = ${expr.eval()}`;
    },
    Mov(_mov, id, _, expr) {
        return `${id.eval()} = ${expr.eval()};`;
    },
    Out(_out, expr) {
        return `console.log(${expr.eval()});`;
    },
    ident(first, rest) {
        return first.sourceString + rest.sourceString;
    },
    Add(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`;
    },
    Sub(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`;
    },
    Mul(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`;
    },
    Div(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`;
    },
    string(_oq, text, _cq) {
        return "\"" + text.sourceString + "\"";
    },
    number(digits) {
        return digits.sourceString;
    }
};
