"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dict = void 0;
exports.dict = {
    Program(sections) {
        let code = '';
        sections.children.map(c => { code += c.eval(); });
        code += '\n main() \n // auto generated by the cruton interpreter';
        return code;
    },
    MAIN(_entry, _, body, _end) {
        return `
    var r1 = null;
    var r2 = null;
    var r3 = null;
    var r4 = null;
    var r5 = null;
    var r6 = null;
    var r7 = null;
    var r8 = null;
    var r9 = null;
    var r10 = null;
function main() {
    ${body.children.map(c => c.eval()).join('   \n')}
}
        `;
    },
    Custom(_, id, _c, body, _end) {
        return `
function ${id.eval()}() {
    ${body.children.map(c => c.eval()).join('\t\n')}
}
        `;
    },
    Call(_call, id) {
        return `${id.eval()}()`;
    },
    Ini(_ini, id) {
        return `let ${id.eval()};`;
    },
    Mov(_mov, id, _, expr) {
        return `${id.eval()} = ${expr.eval()};`;
    },
    Out(_out, expr) {
        return `console.log(${expr.eval()});`;
    },
    ident(first, rest) {
        return first.sourceString + rest.sourceString;
    },
    Add(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`;
    },
    Sub(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`;
    },
    Mul(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`;
    },
    Div(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`;
    },
    string(_oq, text, _cq) {
        return "\"" + text.sourceString + "\"";
    },
    number(digits) {
        return digits.sourceString;
    }
};
