import { grammar } from "./main";

export const semantics = grammar.createSemantics().addOperation('eval', {
    Program(sections) {
        let code = ''
        sections.children.map(c => {code += c.eval()})
        code += '\n main() \n // auto generated by the cruton interpreter'
        return code
    },
})