import { ActionDict } from "ohm-js";

export const dict: ActionDict<any> = {
    Program(sections) {
        let code = ''
        sections.children.map(c => {code += c.eval()})
        code += '\n main() \n // auto generated by the cruton interpreter'
        return code
    },

    MAIN(_entry, _, body, _end) {
        return `
    var r1 = null;
    var r2 = null;
    var r3 = null;
    var r4 = null;
    var r5 = null;
    var r6 = null;
    var r7 = null;
    var r8 = null;
    var r9 = null;
    var r10 = null;
function main() {
    ${body.children.map(c => c.eval()).join('   \n')}
}
        `
    },

    Custom(_, id, _c, body, _end) {
        return `
function ${id.eval()}() {
    ${body.children.map(c => c.eval()).join('\t\n')}
}
        `
    },  

    Expr(or) {
        return or.eval() 
    },

    LogicalOr_or(left, _or, right) {
        return `${left.eval()} || ${right.eval()}`
    },

    LogicalAnd_and(left, _and, right) {
        return `${left.eval()} && ${right.eval()}`
    },

    Primary_parens(_op, expr, _cp) {
        return `(${expr.eval()})`
    },  

    Primary_not(_, expr) {
        return `!${expr.eval()}`
    },

    If(_if, condition, _, body, _stop) {
        return `
if(${condition.eval()}) {
    ${body.children.map(c => c.eval()).join('\n')}
}
        `
    },

    true(_) {
        return `true`
    },

    false(_) {
        return `false`
    },

    Call(_call, id) {
        return `${id.eval()}()`
    },

    Ini(_ini, id) {
        return `let ${id.eval()};`
    },
    
    Mov(_mov, id, _, expr) {
        return `${id.eval()} = ${expr.eval()};`
    },

    Out(_out, expr) {
        return `console.log(${expr.eval()});`
    },

    ident(first, rest) {
        return first.sourceString + rest.sourceString
    },

    Add(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`
    },

    Sub(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`
    },

    Mul(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`
    },

    Div(_add, id, _, expr) {
        return `${id.eval()} = ${id.eval()} + ${expr.eval()}`
    },

    string(_oq, text, _cq) {
        return "\"" + text.sourceString + "\""
    },

    number(digits) {
        return digits.sourceString
    }
}