
    var r1 = null;
    var r2 = null;
    var r3 = null;
    var r4 = null;
    var r5 = null;
    var r6 = null;
    var r7 = null;
    var r8 = null;
    var r9 = null;
    var r10 = null;
function main() {
    let a = 10;   
let b = 10;   
a = a + b   
console.log(a);   
r1 = 2;   
r2 = 2;   
add()   
console.log(r1);   
console.log(!(true || false));   

if(true) {
    console.log("Is true!");
}
           
const c = "Hi, im static, no reassigment >:("   
console.log(c);
}
        
function add() {
    r1 = r1 + r2
}
        
 main() 
 // auto generated by the cruton interpreter