
// DATA SECTION
var globalVar = 10
// DATA SECTION END
        
    var r1 = null;
    var r2 = null;
    var r3 = null;
    var r4 = null;
    var r5 = null;
    var r6 = null;
    var r7 = null;
    var r8 = null;
    var r9 = null;
    var r10 = null;
function main() {
    console.log(globalVar);
}
        
 main() 
 // auto generated by the cruton interpreter