import { ActionDict } from "ohm-js";

export const dict: ActionDict<any> = {
    // MAIN
    //#region 
    Program(sections) {
        let code = ''
        sections.children.map(c => {code += c.eval()})

        code += '\n main() \n // auto generated by the cruton interpreter'
        return code
    },
    //   hehe
    MAIN(_d, _entry, _, body, _end) {
        return `
    var r1 = null;
    var r2 = null;
    var r3 = null;
    var r4 = null;
    var r5 = null;
    var r6 = null;
    var r7 = null;
    var r8 = null;
    var r9 = null;
    var r10 = null;
function main() {
    ${body.children.map(c => c.eval()).join('   \n')}
}
        `
    },
    //#endregion

    // ARRAYS
    //#region 
    Array(_ob, elements, _cb) {
        return `[${elements.children.map(c => c.eval())}]`
    },

    ArrayAccess(id, _ob, expr, _cb) {
        return `${id.eval()}[${expr.eval()}]`
    },
    //#endregion

    // TOP LEVEL SEMANTICS
    //#region 
    nonemptyListOf(_, b, _c) {
        return _.sourceString + b.sourceString
    },

    Expr(or) {
        return or.eval() 
    },

    ident(first, rest) {
        return first.sourceString + rest.sourceString
    },

    comment(_, text) {
        return '// ' + text.sourceString
    },
    //#endregion
    
    // FUNCTIONS
    //#region 
    Call(_call, id, _c, outputTo) {
        if(outputTo.sourceString) {
            return `${outputTo.sourceString} = ${id.eval()}(r1, r2, r3, r4, r5, r6, r7, r8, r9, r10)`
        } else {
            return `${id.eval()}(r1, r2, r3, r4, r5, r6, r7, r8, r9, r10)`
        }
    },

    Custom(_, id, _c, body, _end) {
        return `
function ${id.eval()}() {
    ${body.children.map(c => c.eval()).join('\t\n')}
}
        `
    }, 
    //#endregion

    // VARIABLES
    //#region 
    GLOBALS(_d, _data, _, body, _end) {
        return `
// DATA SECTION
${body.children.map(c => c.eval()).join('\t\n')}
// DATA SECTION END
        `
    },

    GlobalDecl(id, _, expr, _c) {
        return `var ${id.eval()} = ${expr.eval()}`
    },

    Ini(_ini, id, _, expr) {
        if(expr.sourceString) {
            return `let ${id.eval()} = ${expr.eval()};`
        } else {
            return `let ${id.eval()};`
        }
    },

    Static(_static, id, _, expr) {
        return `const ${id.eval()} = ${expr.eval()}`
    },
    
    Mov(_mov, id, _, expr) {
        return `${id.eval()} = ${expr.eval()};`
    },
    //#endregion

    // BOOLEAN LOGIC
    //#region 
    If(_if, condition, _, body, _stop) {
        return `
if(${condition.eval()}) {
    ${body.children.map(c => c.eval()).join('\n')}
}
        `
    },

    Primary_not(_, expr) {
        return `!${expr.eval()}`
    },

    LogicalOr_or(left, _or, right) {
        return `${left.eval()} || ${right.eval()}`
    },

    LogicalAnd_and(left, _and, right) {
        return `${left.eval()} && ${right.eval()}`
    },

    true(_) {
        return `true`
    },

    false(_) {
        return `false`
    },

    Comparisons_equality(left, _, right) {
        return `${left.eval()} == ${right.eval()}`
    },

    Comparisons_greater(left, _, right) {
        return `${left.eval()} > ${right.eval()}`
    },

    Comparisons_less(left, _, right) {
        return `${left.eval()} < ${right.eval()}`
    },
    //#endregion

    // INBUILTS
    //#region 
    Import(_import, modulename,  _as, id) {
        return `var ${id.eval()} = require(${modulename.eval()})`
    },

    Out(_out, expr) {
        return `console.log(${expr.eval()});`
    },
    //#endregion

    // LOOPS
    //#region 
    While(_loop, _, body, _if, cond) {
        return `
        while(${cond.eval()}) {
            ${body.children.map(c => c.eval()).join('\t\n')}
        }
        `
    },
    //#endregion

    // MATH
    //#region 
    Primary_parens(_op, expr, _cp) {
        return `(${expr.eval()})`
    },  

    Additive_plus(left, _, right) {
        return `${left.eval()} + ${right.eval()}`
    },

    Additive_minus(left, _, right) {
        return `${left.eval()} - ${right.eval()}`
    },

    Add(_add, id, _, expr) {
        return `${id.eval()} += ${expr.eval()}`
    },

    Sub(_add, id, _, expr) {
        return `${id.eval()} -= ${expr.eval()}`
    },

    Mul(_add, id, _, expr) {
        return `${id.eval()} *= ${expr.eval()}`
    },

    Div(_add, id, _, expr) {
        return `${id.eval()} /= ${expr.eval()}`
    },

    string(_oq, text, _cq) {
        return "\"" + text.sourceString + "\""
    },

    number(digits) {
        return digits.sourceString
    }
    //#endregion 
}